### ISSUE TITLE
Completar instrucciones

### ISSUE THREAD

**Issue by oriavel** [oriavel/akelarre#51]
- Añadir instrucciones necesarias para que un jugador pueda seguir el juego sin problemas

- Quitar fondo blanco de las imágenes

- Ser más descriptivos

**Comment by pali509** [comment]
-Añadida la funcionalidad de escape a instrucciones, falta encontrar imagen buena de tecla esc

-Para mi el fondo blanco no queda mal lol

-Añadido a descripción que los minijuegos no están desde el principio, yo creo que no hace falta poner nada mas.
