### ISSUE TITLE
Generar personajes, backgrounds, ambientación y texturas

### ISSUE THREAD

**Issue by oriavel** [oriavel/akelarre#6]
Nutrir assests en gral
- Diseñar y pintar las cosas
- Confirmarlas entre todos
- Subirlo a main

**Comment by pali509** [comment]
![Prota](https://user-images.githubusercontent.com/79701191/225573837-10d45f72-7dd4-43a1-95f7-47753ca2faa3.PNG)

Primer diseño de la protagonista terminado :)

**Comment by pali509** [comment]
![image](https://user-images.githubusercontent.com/79701191/226315819-1893c5df-cc83-48d3-b9d2-6247161f42dc.png)

Cueva hecha :D
